apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: rtscs-services
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: health
  selector:
    app: inventory-service
