apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: rtscs-services
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  selector:
    app: order-service
