
spring:
  application:
    name:
      order-service
  jpa:
    hibernate:
      ddl-auto: drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://ep-aged-hill-a1uo9k1a-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_7RjYqSCL6yFr&sslmode=require&channelBinding=require
    driver-class-name: org.postgresql.Driver